### ISSUE TITLE
Why use nginx and Caddy?

### ISSUE THREAD

**Issue by zilexa** [DoTheEvo/selfhosted-apps-docker#15]
Your solution can be simplified by using Caddy(V2) for both purposes.

**Comment by DoTheEvo** [comment]
I am not going to dig in to how to exactly to setup webserver for nextcloud app when the people who make nextcloud already did the work and tested it thoroughly.

Don't really see any simplification either. Containers spin up by compose "recipe" does not matter if two caddies or one of them is nginx.

**Comment by zilexa** [comment]
What I meant was 1 Caddy container can do both. Since you already install Caddy, it doesn't make sense anymore to also install NGINX. That's all. 
I'm going to try it see if it works.

**Comment by DoTheEvo** [comment]
I am no expert, but I feel it goes so extremely against philosophy of docker
These guys put even fucking cron as a separate container... 

so obviously container that does reverse proxy will do just that one job
and container that is part of nextcloud stack, whos job is to shows nextcloud content will do just that
