### ISSUE TITLE
tor hidden service support

### ISSUE THREAD

**Issue by r0qstr** [DoTheEvo/selfhosted-apps-docker#16]
I am wondering how one would add support for another domain in the caddyfile? What do I have to keep in mind with the tor config? the following did not work:

torrc:
HiddenServiceDir /var/lib/tor/hidden_service/
HiddenServicePort 80 127.0.0.1:80

xyz123.onion:80 nextcloud.{$MY_DOMAIN} {
    reverse_proxy nextcloud-web:80
    header Strict-Transport-Security max-age=31536000;
...
}

**Comment by DoTheEvo** [comment]
dunno, try caddy forums

[https://caddy.community/](https://caddy.community/)
