### ISSUE TITLE
On Raspberry Pi 4 

### ISSUE THREAD

**Issue by noone-g** [DoTheEvo/selfhosted-apps-docker#21]
First of all, thanks for the guide.

I tried to implement this on rpi4 by changing the image from "mariadb" to "tobi312/rpi-mariadb:latest" since mariadb doesn't support arm natively. Except for that, nothing I touched.

I couldn't create the nextcloud administrative account and keep getting the following error.

"SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again"

Thanks in advance for any help.

**Comment by sroener** [comment]
I had the same problem. I assume it is a problem with the arm 32bit mariadb image. As I was on a fresh install, I switched over to a 64 bit os and install the regular version of mariadb. Afterwards everything worked as expected.

**Comment by noone-g** [comment]
> 
> 
> I had the same problem. I assume it is a problem with the arm 32bit mariadb image. As I was on a fresh install, I switched over to a 64 bit os and install the regular version of mariadb. Afterwards everything worked as expected.

Thanks for the tip. Did you install raspbian 64 os (beta) or Ubuntu 64 for rpi 4? If so, what mariadb tag did you use?

Thanks in advance

**Comment by sroener** [comment]
I Installed dietpi 64 bit. AFAIK its based on raspbian 64 minimal with some additional utility scripts. I didn't use any tag, just `mariadb`. It pulled the right image automatically.

**Comment by noone-g** [comment]
Thanks.

I will try this during the week and let you know the results.

**Comment by noone-g** [comment]
Thanks.

It worked.
I use dietpi 64 now.

**Comment by sroener** [comment]
Glad it worked ;) 
I guess the issue can be closed now @DoTheEvo
