### ISSUE TITLE
Caddy version 2.6.2 > 2.7.5 for cloudflare dns challenge

### ISSUE THREAD

**Issue by semiligneous** [DoTheEvo/selfhosted-apps-docker#43]
I'm following the caddy_v2 guide, and wanting to add Cloudflare DNS challenge, When I docker compose up it eventually fails with:

```
126.7 2024/05/15 11:56:37 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddy-dns/cloudflare github.com/caddyserver/caddy/v2@v2.6.2 
128.1 go: downloading github.com/caddy-dns/cloudflare v0.0.0-20240405130444-44030f9306f4
132.5 go: github.com/caddy-dns/cloudflare@upgrade (v0.0.0-20240405130444-44030f9306f4) requires github.com/caddyserver/caddy/v2@v2.7.5, not github.com/caddyserver/caddy/v2@v2.6.2
132.5 2024/05/15 11:56:43 [FATAL] exit status 1
------
failed to solve: process "/bin/sh -c xcaddy build     --with github.com/caddy-dns/cloudflare" did not complete successfully: exit code: 1
```

since it is quite clear in the output:

**requires** github.com/caddyserver/caddy/v2@**v2.7.5**, **not** github.com/caddyserver/caddy/v2@v**2.6.2**

I was able to fix by altering dockerfile-caddy/Dockerfile, replacing 2.6.2 with 2.7.5, and trying again.

This time it all works.

However, how do I know 2.7.5 is the best/latest/correct version? And also, will I need to continue manually incrementing this every time it gets "old"? Is there a way to simply replace with "latest" or is that ill-advised?

Thanks for all the guides and help!

**Comment by DoTheEvo** [comment]
updated to 2.8.4
thnx
