### ISSUE TITLE
Fix for being unable to connect to a desktop client

### ISSUE THREAD

**Issue by QEDeD** [DoTheEvo/selfhosted-apps-docker#8]
There seems to be a general bug with authorizing desktop clients when forcing HTTPS, as this setup does. I've posted a way to fix the issue that is applicable to this setup over here: https://github.com/nextcloud/desktop/issues/1521#issuecomment-642083802 

Not sure if there's a better way to fix it, but thought it might be worth referencing somewhere in this documentation :)

**Comment by DoTheEvo** [comment]
so that override that is mentioned in troubleshooting...
