### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by maltokyo** [DoTheEvo/selfhosted-apps-docker#9]
In here:

https://github.com/DoTheEvo/selfhosted-apps-docker/tree/master/caddy_v2#--create-docker-composeyml

I guess MY_DOMAIN should be $MY_DOMAIN

**Comment by DoTheEvo** [comment]
one would think so, but test it... 
change it to $MY_DOMAIN or ${MY_DOMAIN}
exec in to container using [ctop](https://github.com/bcicen/ctop) and run `printenv`
only plain works...

I guess it is some substitution or short form
and in full it should be or whatever

    environment:
      - MY_DOMAIN=$MY_DOMAIN

I might have know why and how it worked  few months back, or I might have not...  i dont remember now and quick google was not a success
